name: Node.js Package Publish
description: "Publish Node.js package to Github Package Registry"
inputs:
  token:
    description: "A Github PAT"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        registry-url: "https://npm.pkg.github.com/"
        always-auth: true
    - name: Update package.json name 📝
      uses: jossef/action-set-json-field@v1
      with:
        file: package.json
        field: name
        value: "@${{ github.repository_owner }}/${{ github.event.repository.name }}"
    - name: 😺 GitHub publish
      continue-on-error: true
      env:
        OWNER: ${{ github.repository_owner }}
        NPM_TOKEN: ${{ inputs.token }}
      run: |
        echo "@${OWNER}:registry=https://npm.pkg.github.com" >> .npmrc
        echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" >> .npmrc
        cat .npmrc
        npm publish
      shell: bash
