name: Node CI/CD

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  node:
    uses: actionsaustenstone/.github/.github/workflows/node-package.yml@main
    with:
      context: ${{ toJson(github) }}
