name: Node CI
description: "Build, test, and lint Node.js project"

inputs:
  node-version:
    description: "Node.js version"
    required: false
    default: "16"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
    - run: npm ci
      shell: bash
    - run: npm run build
      shell: bash
    - run: npm run test
      shell: bash
    - run: npm run lint
      shell: bash
